# main settingn for both
server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#read local files for password
spring.config.import=optional:classpath:application-local.properties